### ISSUE TITLE
javax.mail.MessagingException: Missing start boundary

### ISSUE THREAD

**Issue by dylan96dashintha** [adobe/pdfservices-java-sdk-samples#9] opened 2020-12-11 05:28 UTC
In my Java Struts2 project, I have a requirement to convert PDF to DOCX and PPTX format. I used the Adobe Document service SDK to do the conversion. So I used the jars that are needed to do the conversion and build a new java project and run the project. The conversion is done nicely. But when I integrate that into my Java Struts2 project and run it, there is always an exception occurs that I could not handle.

Exception is,

`Exception in thread "main" net.jodah.failsafe.FailsafeException: javax.mail.MessagingException: Missing start boundary
at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:323)
at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:71)
at com.adobe.platform.operation.internal.http.HttpClientWrapper.send(HttpClientWrapper.java:120)
at com.adobe.platform.operation.internal.api.CPFApi.cpfStatusApi(CPFApi.java:127)
at com.adobe.platform.operation.internal.api.FileDownloadApi.downloadAndSave(FileDownloadApi.java:42)
at com.adobe.platform.operation.pdfops.ExportPDFOperation.execute(ExportPDFOperation.java:137)
at com.axissource.symbiosis.outputgen.outputgenerator.ExportPDFToDOCX.main(ExportPDFToDOCX.java:39)Caused by: javax.mail.MessagingException: Missing start boundary
at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:284)
at javax.mail.internet.MimeMultipart.getCount(MimeMultipart.java:158)
at com.adobe.platform.operation.internal.http.MultiPartHttpResponse.parseInlineResponseData(MultiPartHttpResponse.java:70)
at com.adobe.platform.operation.internal.http.MultiPartHttpResponse.<init>(MultiPartHttpResponse.java:60)
at com.adobe.platform.operation.internal.http.HttpClientWrapper.handleResponse(HttpClientWrapper.java:241)
at com.adobe.platform.operation.internal.http.HttpClientWrapper.executeRequest(HttpClientWrapper.java:152)
at com.adobe.platform.operation.internal.http.HttpClientWrapper.lambda$send$0(HttpClientWrapper.java:120)
at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)`

can you help me to avoid this exception?

**Comment by namangupta2100** [comment] 2021-08-02 16:12
@dylan96dashintha - Hi. Could you please share some sample that we can run and reproduce the problem. Or a quick guideline to setup the sample Java struts2 project.
That would help us with the quick turnaround on the issue.

**Comment by anubhav-mhjn** [comment] 2022-04-25 07:16
Closing this issue since it has been idle since long. Please feel free to reopen the issue if required.

**Closed by anubhav-mhjn** 2022-04-25 07:16 UTC
